#! /bin/bash

source 0-setenv.sh

scp -P $SSH_PORT -i $SSH_CERT markets.csv $SSH_USER@$SSH_HOST:$SSH_REMOTE_DIR
scp -P $SSH_PORT -i $SSH_CERT 0-*.sh $SSH_USER@$SSH_HOST:$SSH_REMOTE_DIR
scp -P $SSH_PORT -i $SSH_CERT 1-*.sh $SSH_USER@$SSH_HOST:$SSH_REMOTE_DIR
scp -P $SSH_PORT -i $SSH_CERT 2-*.sh $SSH_USER@$SSH_HOST:$SSH_REMOTE_DIR
scp -P $SSH_PORT -i $SSH_CERT 3-*.sh $SSH_USER@$SSH_HOST:$SSH_REMOTE_DIR
scp -P $SSH_PORT -i $SSH_CERT -r templates/ $SSH_USER@$SSH_HOST:$SSH_REMOTE_DIR
